board:

  tileset :
    - '+-----+-----+-----+'
    - '|     |     |     |'
    - '|     |     |     |'
    - '|     |     |     |'
    - '+-----+-----+-----+'
    - '|     |     |     |'
    - '|     |     |     |'
    - '|     |     |     |'
    - '+-----+-----+-----+'
    - '|     |     |     |'
    - '|     |     |     |'
    - '|     |     |     |'
    - '+-----+-----+-----+'

  player_turns:
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]

address_table:

  rows:
    top:
      - 2
      - 0
    mid:
      - 6
      - 1
    bot:
      - 10
      - 2

  cols:
    left:
      - 3
      - 0
    mid:
      - 9
      - 1
    right:
      - 15
      - 2
