tarifs:
  short:
    apr:          0.20
    max_loan:     1000
    min_loan:     500
    max_duration: 0.5
  medium:
        apr:          0.15
        max_loan:     1500
        min_loan:     950
        max_duration: 0.5
  long:
        apr:          0.05
        max_loan:     1000000
        min_loan:     800000
        max_duration: 5
id_methods:
  phone: ^\+\d+\(\d{3}\)\d{3}-\d{2}-\d{2}$
  email: (\d*[A-z]*\d*\.)*(\d*[A-z]*\d*)+@(\d*[A-z]\d*)+\.[a-z][a-z]+$
  post:  ^\d{8}
promts:
  hi:              |
    /#########################################\
    |                                         |
    | Welcome to "Practically for free!" LTD! |
    |                  *-*-*                  |
    |            Press 's' to start..         |
    |                  ..processing the loan. |
    |            Press 'h' for help.          |
    \#########################################/
  help:            |
    /+++++++++++++++++++++++++++++++++++++++++\
    |  Choose your action:                    |
    |            Press 's' to [re]start..     |
    |                  ..processing the loan. |
    |            Press 'l' to list loan..     |
    |                               ..tarifs. |
    |            Press 'h' for this message.  |
    |            Press 'c' to check current.. |
    |                        ..configuration. |
    |            Press 'q' to exit.           |
    \+++++++++++++++++++++++++++++++++++++++++/
  invalid_answer:  |
    /#########################################\
    |                    !E!                  |
    |   Invalid answer! Press 'h' for help.   |
    |                    !E!                  |
    \#########################################/
  promt_id_method: |
    /+++++++++++++++++++++++++++++++++++++++++\
    |  Choose your identification:            |
    |            Enter 'phone' to id..        |
    |                      ..by phone number. |
    |            Enter 'email' to id..        |
    |                      ..by email.        |
    |            Enter 'post' to id..         |
    |                       ..by post number. |
    \+++++++++++++++++++++++++++++++++++++++++/
  confirm_quit:    |
    /#########################################\
    |                                         |
    |        DO YOU REALLY WANT TO QUIT?      |
    |                   y/n                   |
    \#########################################/
  top_line:        |
    /#########################################\
  bot_line:        |
    \#########################################/
  bye: 'Goodbye, '
  enter_name:      |
    /#########################################\
    |        Please, enter your name:         |
    \#########################################/
